//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.04 at 10:44:38 AM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://kuler.adobe.com/kuler/API/rss/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.metatrope.kuler.theme;
