//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.04 at 10:23:28 AM EDT 
//


package com.metatrope.kuler.theme;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ThemeItem complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ThemeItem">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="themeID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="themeTitle" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="themeImage" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="themeAuthor" type="{http://kuler.adobe.com/kuler/API/rss/}themeAuthor"/>
 *         &lt;element name="themeTags" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="themeRating" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="themeDownloadCount" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="themeCreatedAt" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="themeEditedAt" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="themeSwatches" type="{http://kuler.adobe.com/kuler/API/rss/}themeSwatches"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ThemeItem", propOrder = {
    "themeID",
    "themeTitle",
    "themeImage",
    "themeAuthor",
    "themeTags",
    "themeRating",
    "themeDownloadCount",
    "themeCreatedAt",
    "themeEditedAt",
    "themeSwatches"
})
public class ThemeItem {

    protected int themeID;
    @XmlElement(required = true)
    protected String themeTitle;
    @XmlElement(required = true)
    protected String themeImage;
    @XmlElement(required = true)
    protected ThemeAuthor themeAuthor;
    @XmlElement(required = true)
    protected String themeTags;
    protected int themeRating;
    protected int themeDownloadCount;
    protected int themeCreatedAt;
    protected int themeEditedAt;
    @XmlElement(required = true)
    protected ThemeSwatches themeSwatches;

    /**
     * Gets the value of the themeID property.
     * 
     */
    public int getThemeID() {
        return themeID;
    }

    /**
     * Sets the value of the themeID property.
     * 
     */
    public void setThemeID(int value) {
        this.themeID = value;
    }

    /**
     * Gets the value of the themeTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getThemeTitle() {
        return themeTitle;
    }

    /**
     * Sets the value of the themeTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setThemeTitle(String value) {
        this.themeTitle = value;
    }

    /**
     * Gets the value of the themeImage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getThemeImage() {
        return themeImage;
    }

    /**
     * Sets the value of the themeImage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setThemeImage(String value) {
        this.themeImage = value;
    }

    /**
     * Gets the value of the themeAuthor property.
     * 
     * @return
     *     possible object is
     *     {@link ThemeAuthor }
     *     
     */
    public ThemeAuthor getThemeAuthor() {
        return themeAuthor;
    }

    /**
     * Sets the value of the themeAuthor property.
     * 
     * @param value
     *     allowed object is
     *     {@link ThemeAuthor }
     *     
     */
    public void setThemeAuthor(ThemeAuthor value) {
        this.themeAuthor = value;
    }

    /**
     * Gets the value of the themeTags property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getThemeTags() {
        return themeTags;
    }

    /**
     * Sets the value of the themeTags property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setThemeTags(String value) {
        this.themeTags = value;
    }

    /**
     * Gets the value of the themeRating property.
     * 
     */
    public int getThemeRating() {
        return themeRating;
    }

    /**
     * Sets the value of the themeRating property.
     * 
     */
    public void setThemeRating(int value) {
        this.themeRating = value;
    }

    /**
     * Gets the value of the themeDownloadCount property.
     * 
     */
    public int getThemeDownloadCount() {
        return themeDownloadCount;
    }

    /**
     * Sets the value of the themeDownloadCount property.
     * 
     */
    public void setThemeDownloadCount(int value) {
        this.themeDownloadCount = value;
    }

    /**
     * Gets the value of the themeCreatedAt property.
     * 
     */
    public int getThemeCreatedAt() {
        return themeCreatedAt;
    }

    /**
     * Sets the value of the themeCreatedAt property.
     * 
     */
    public void setThemeCreatedAt(int value) {
        this.themeCreatedAt = value;
    }

    /**
     * Gets the value of the themeEditedAt property.
     * 
     */
    public int getThemeEditedAt() {
        return themeEditedAt;
    }

    /**
     * Sets the value of the themeEditedAt property.
     * 
     */
    public void setThemeEditedAt(int value) {
        this.themeEditedAt = value;
    }

    /**
     * Gets the value of the themeSwatches property.
     * 
     * @return
     *     possible object is
     *     {@link ThemeSwatches }
     *     
     */
    public ThemeSwatches getThemeSwatches() {
        return themeSwatches;
    }

    /**
     * Sets the value of the themeSwatches property.
     * 
     * @param value
     *     allowed object is
     *     {@link ThemeSwatches }
     *     
     */
    public void setThemeSwatches(ThemeSwatches value) {
        this.themeSwatches = value;
    }

}
